-- SANVIC seed data
-- Generated from src/data/*.ts (the app's bundled fallback content) so the
-- database starts with exactly what the demo shows. Idempotent-ish: assumes
-- empty tables; wipe with `truncate places cascade` before re-running.

-- places
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Long Beach', 'long-beach', 'beaches', 'San Vicente''s signature coastline: a 14-kilometre sweep of golden sand with gentle water, coconut edges, and long stretches that still feel undeveloped compared with busier Palawan towns.', 'The longest white-sand beach in the Philippines, minutes from town.', 10.4962, 119.2607, 'Poblacion – New Agutaya', '/images/san-vicente-long-beach.jpg', 4.9, null, 'Sunrise for quiet, late afternoon for color', 'Nov–May', 10, null, array['swimming','sunset','walking','quiet'], true, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Itaytay Beach', 'itaytay-beach', 'beaches', 'The Port Barton village beachfront: a calm bay lined with outrigger boats, beach bars, and simple restaurants. The easiest place in San Vicente to swim, eat, and watch the boats come in without going anywhere.', 'Calm bay swimming right off the village, with food steps away.', 10.4581, 119.2109, 'Port Barton', '/images/san-vicente-port-barton.jpg', 4.6, null, 'Morning before boats depart, or golden hour', 'Dec–May', 80, null, array['swimming','boats','village','easy'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('White Beach', 'white-beach-port-barton', 'beaches', 'A quiet cove south of Port Barton village, reached by a short scenic walk or a five-minute boat ride. Fine pale sand, shady palms, and far fewer people than the village beach.', 'A quieter cove a short walk from Port Barton village.', 10.4443, 119.2172, 'Port Barton', null, 4.7, null, 'Midday when the shallows glow', 'Dec–May', 95, '15 min walk or 5 min boat from Port Barton', array['quiet','swimming','cove','walk'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Alimanguan Beach', 'alimanguan-beach', 'beaches', 'The wilder northern end of San Vicente''s coast near Alimanguan village. Open surf-brushed sand, fishing boats, and almost nobody around — a real edge-of-the-map feeling.', 'Wide, empty northern sand for travelers who want space.', 10.5836, 119.3242, 'Alimanguan', null, 4.5, null, 'Late afternoon', 'Nov–May', 35, null, array['quiet','wild','walking','local'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Boayan Island', 'boayan-island', 'islands', 'A remote island off San Vicente''s northwest coast with clear water, forested hills, and small coves. A frontier feeling for travelers who want a quieter island escape than the tour circuits.', 'The remote island escape — clear coves, almost no crowds.', 10.55, 119.09, 'New Canipo', '/images/san-vicente-boayan.jpg', 4.7, null, 'Full-day trip, leave by 8am', 'Mar–May', null, 'By arranged boat from Poblacion or New Canipo', array['remote','snorkeling','day-trip','boat'], true, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('German Island', 'german-island', 'islands', 'A small island stop on the classic Port Barton tour, known for clear shallows, an easy snorkeling reef, and sandbars at low tide. Turtles are often sighted nearby — keep your distance and never touch.', 'Clear shallows and turtle sightings on the classic boat route.', 10.4586, 119.0705, 'Port Barton', '/images/island-boats-aerial.jpg', 4.6, null, 'Morning tours get the calmest water', 'Dec–May', null, '30–45 min by boat from Port Barton', array['snorkeling','turtles','tour','sandbar'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Inaladelan Island', 'inaladelan-island', 'islands', 'A polished island stop from Port Barton with bright sand, clear water, hammocks, and an easy picnic atmosphere. Camping overnight is possible with the caretakers — one of Palawan''s simplest island-sleep experiences.', 'Bright sand, hammocks, and the easiest island picnic day.', 10.4643, 119.0447, 'Port Barton', '/images/kayak-lagoon.jpg', 4.7, null, 'Any clear day; overnight camping for stargazers', 'Dec–May', null, 'By boat from Port Barton, usually on tours', array['picnic','camping','snorkeling','tour'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Exotic Island Sandbar', 'exotic-island-sandbar', 'islands', 'A slim sandbar island between Port Barton and the open sea that appears and shrinks with the tide. Boats stop for photos, quick swims, and the strange pleasure of standing on sand in the middle of the sea.', 'Stand on a sandbar in the middle of the sea at low tide.', 10.4306, 119.1264, 'Port Barton', null, 4.5, null, 'Low tide — ask your boatman to time it', 'Dec–May', null, 'Island-hopping stop from Port Barton', array['sandbar','photos','tour','tide'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Pamuayan Falls', 'pamuayan-falls', 'nature', 'A freshwater waterfall near Port Barton reached by a short inland ride and a forest walk. A cool plunge pool under the drop — ideal when you need a break from saltwater and beach heat.', 'A cool freshwater plunge 25 minutes from Port Barton.', 10.4808, 119.2383, 'Pamuayan', '/images/san-vicente-waterfalls.jpg', 4.5, null, 'After light rain for stronger flow', 'Year-round', 60, '25 min from Port Barton by trail or motorbike', array['waterfall','freshwater','hike','shade'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Bato ni Ningning', 'bato-ni-ningning', 'nature', 'A scenic rock viewpoint above the coast where Long Beach, the green hills, and the scale of the municipality reveal themselves. The classic San Vicente panorama shot.', 'The viewpoint that shows you all 14 km of Long Beach at once.', 10.5634, 119.3092, 'Sto. Niño', null, 4.6, null, 'Late afternoon for soft light', 'Nov–May', 35, null, array['viewpoint','photos','sunset','short-hike'], true, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Little Baguio Falls', 'little-baguio-falls', 'nature', 'A tiered jungle waterfall inland from the Poblacion side, with cool pools and a forest picnic feel. Less visited than Pamuayan — bring grippy sandals and pack out everything you bring in.', 'Tiered jungle pools on the quiet inland side.', 10.5089, 119.3306, 'Kemdeng', null, 4.4, null, 'Morning, before day-trip heat', 'Jun–Nov flows strongest', 30, null, array['waterfall','jungle','swimming','quiet'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('San Vicente Poblacion', 'san-vicente-poblacion', 'culture', 'The practical center of San Vicente: transport terminals, the public market, municipal services, small eateries, and everyday local life away from the island-hopping crowds. Every SANVIC travel time is measured from here.', 'The town center — market, transport, and everyday Palawan life.', 10.5318, 119.2822, 'Poblacion', null, 4.3, null, 'Morning market hours', 'Year-round', 0, null, array['market','transport','local-life','supplies'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Port Barton Village', 'port-barton-village', 'culture', 'A relaxed fishing village turned traveler hub inside San Vicente. Sandy lanes, island-hopping boats, beachfront cafés, and a slower rhythm made for unhurried travelers. Bring cash — ATMs are unreliable.', 'San Vicente''s laid-back traveler village and boat-tour base.', 10.4102, 119.1771, 'Port Barton', '/images/san-vicente-port-barton.jpg', 4.8, null, 'Golden hour on the beachfront', 'Dec–May', 80, null, array['village','boats','nightlife-lite','base'], true, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Poblacion Market Eateries', 'poblacion-market-eateries', 'food', 'The cluster of carinderias and grill stalls around the public market. Grilled fish straight off the boats, silog breakfasts, and the cheapest honest meal in the municipality. Cash only, lunch sells out early.', 'Grilled catch-of-the-day beside the market for pocket change.', 10.5301, 119.2835, 'Poblacion', '/images/street-food-skewers.jpg', 4.4, 1, 'Lunch, before 1pm', 'Year-round', 0, null, array['local-food','seafood','budget','cash-only'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Long Beach Grill Row', 'long-beach-grill-row', 'food', 'The strip of beachfront grills and family restaurants along the New Agutaya stretch of Long Beach. Kinilaw, grilled squid, halo-halo, and cold drinks with your feet still in the sand.', 'Fresh kinilaw and grilled squid with sand under your feet.', 10.5122, 119.2704, 'New Agutaya', null, 4.5, 2, 'Sunset dinner', 'Nov–May', 8, null, array['seafood','beachfront','sunset','dinner'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Jambalaya Café', 'jambalaya-cafe', 'food', 'A Port Barton beachfront staple for big breakfasts, fruit shakes, and relaxed dinners. One of the village''s most dependable kitchens after a day on the boats.', 'Port Barton''s dependable beachfront kitchen — great after tours.', 10.4576, 119.2119, 'Port Barton', null, 4.6, 2, 'Breakfast before tours, dinner after', 'Year-round', 80, null, array['breakfast','shakes','beachfront','traveler-favorite'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Long Beach Garden Stays', 'long-beach-garden-stays', 'stays', 'A quiet cluster of garden cottages and small resorts along the central Long Beach stretch. Direct beach access, hammocks, and real silence at night — the anti-resort resort experience.', 'Garden cottages with direct access to the empty 14-km beach.', 10.5049, 119.2652, 'New Agutaya', null, 4.6, 2, 'Book ahead Dec–Apr', 'Nov–May', 9, null, array['beachfront','quiet','cottages','couples'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Port Barton Bayfront Stays', 'port-barton-bayfront-stays', 'stays', 'Beachfront guesthouses and small resorts on Itaytay Beach, steps from the boats. The social base: easy tours, easy food, easy sunsets. Book early in high season.', 'Wake up steps from the boats and the bay.', 10.4589, 119.2101, 'Port Barton', null, 4.5, 2, 'Book ahead Dec–Apr', 'Dec–May', 80, null, array['beachfront','social','tours','budget-to-mid'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Poblacion Café Corner', 'poblacion-cafe-corner', 'work', 'The small set of cafés around Poblacion with dependable signal, real espresso, and power outlets. San Vicente''s best bet for a focused laptop morning before an afternoon on Long Beach.', 'Espresso, outlets, and the town''s steadiest signal.', 10.5296, 119.2811, 'Poblacion', null, 4.2, 2, 'Weekday mornings', 'Year-round', 0, null, array['wifi','coffee','outlets','aircon'], false, true);
insert into public.places (name, slug, category, description, short_reason, latitude, longitude, barangay, image_url, rating, price_level, best_time, best_season, travel_minutes_from_poblacion, travel_note, tags, is_featured, is_active) values ('Port Barton Garden Cafés', 'port-barton-garden-cafes', 'work', 'Shaded garden cafés a street back from Itaytay Beach where nomads settle in with smoothie bowls and laptops. Signal is decent, power can flicker — save often, swim at lunch.', 'Garden-shade laptop mornings, thirty steps from the sea.', 10.4571, 119.2131, 'Port Barton', null, 4.3, 2, 'Mornings before heat', 'Dec–May', 80, null, array['wifi','nomad','garden','smoothies'], false, true);

-- recommendations
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'long-beach'), 'morning', 'Best beach this morning', 'Glassy water and an empty 14-km shoreline before 10am — the best swim window of the day.', 1, 'clear', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'poblacion-cafe-corner'), 'morning', 'Quiet place to work', 'Real espresso, outlets, and the town''s steadiest signal — clear your inbox before beach hours.', 3, 'any', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = null), 'morning', 'Local breakfast', 'Silog plates and market coffee where the fishermen eat. Go before 9am for the full scene.', 2, 'any', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'german-island'), 'morning', 'Island trip worth booking', 'Morning boats get the calmest water for the turtle reef. Book at the beachfront kiosks today.', 2, 'clear', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'white-beach-port-barton'), 'midday', 'Best beach right now', 'The shallows glow brightest at midday, and the palms give real shade when the sun peaks.', 1, 'clear', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'pamuayan-falls'), 'midday', 'Beat the heat', 'A cold freshwater plunge under forest shade — the smartest place to be at peak heat.', 2, 'any', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = null), 'midday', 'Lunch like a local', 'Grilled catch-of-the-day beside the market — the good stuff sells out by 1pm.', 2, 'any', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'long-beach'), 'afternoon', 'Golden-hour walk', 'Start near Poblacion and walk south — the light softens and the beach empties as you go.', 2, 'clear', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'bato-ni-ningning'), 'afternoon', 'The panorama shot', 'Late-afternoon light turns the whole coastline gold from up here. Allow 35 minutes to get up.', 1, 'clear', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'long-beach-grill-row'), 'afternoon', 'Early dinner spot', 'Claim a beachfront table before the sunset crowd; the kinilaw is made to order.', 3, 'any', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'long-beach'), 'sunset', 'Best sunset spot tonight', 'The west-facing sand line means an unobstructed horizon sunset almost anywhere on the beach.', 1, 'any', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'bato-ni-ningning'), 'sunset', 'Sunset from above', 'Watch the sun drop behind Boayan from the rock — bring a light for the way down.', 2, 'clear', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'long-beach-grill-row'), 'sunset', 'Dinner with the show', 'Grilled squid and a cold drink while the sky does its thing 20 meters away.', 2, 'any', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'port-barton-village'), 'evening', 'Evenings with a pulse', 'Beach bonfires and low-key beachfront bars — the closest San Vicente gets to nightlife.', 1, 'any', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'long-beach-garden-stays'), 'evening', 'Where to sleep well', 'Garden cottages on the quiet stretch — fall asleep to waves, not karaoke.', 2, 'any', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'poblacion-cafe-corner'), 'rainy', 'Rainy-day base', 'Dry, caffeinated, connected. Wait out the cell here — coastal rain usually passes within hours.', 1, 'rain', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'pamuayan-falls'), 'rainy', 'After the rain', 'Light rain feeds the falls — go once it eases for the strongest flow of the week. Skip during heavy rain.', 2, 'rain', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = null), 'rainy', 'Comfort food weather', 'Hot lugaw and fresh lumpia under the market roof while it pours.', 3, 'rain', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'boayan-island'), 'any', 'Plan ahead: the remote one', 'Boayan needs an arranged boat and a calm-sea day — worth lining up two days out.', 5, 'clear', true);
insert into public.recommendations (place_id, context_type, title, reason, priority, weather_condition, is_active) values ((select id from public.places where slug = 'port-barton-bayfront-stays'), 'any', 'Stay recommendation', 'Bayfront rooms steps from the boats — the easy base if tours are your plan.', 6, 'any', true);


-- local updates (relative timestamps keep the demo feeling current)
insert into public.local_updates (title, body, category, location, severity, source, created_at, valid_until) values
('Long Beach: calm and clear', 'Gentle water on the central stretch this morning, light onshore breeze after lunch. Good swimming until mid-afternoon; the New Agutaya section is quietest.', 'beach', 'Long Beach', 'good', 'SANVIC conditions desk', now() - interval '2 hours', now() + interval '10 hours'),
('Tonight''s sunset window', 'Sun drops around 6:05pm with a mostly open western horizon. Best positions: anywhere on Long Beach, or Bato ni Ningning if you leave Poblacion by 4:45pm.', 'sunset', 'West coast', 'info', 'SANVIC conditions desk', now() - interval '3 hours', now() + interval '8 hours'),
('Island hopping: boats running', 'Port Barton tours departing normally. Morning departures recommended — afternoon chop has been picking up near German Island this week. Bring cash for environmental fees.', 'island-hopping', 'Port Barton', 'good', 'Boat operators'' association', now() - interval '5 hours', now() + interval '20 hours'),
('Poblacion–Port Barton road: clear', 'The inland road is dry and passable end to end. Vans running on schedule, about 1h20 door to door. Last van back to Poblacion leaves Port Barton at 4pm.', 'travel', 'San Vicente–Port Barton road', 'info', 'Transport terminal', now() - interval '8 hours', now() + interval '30 hours'),
('Food tip: tuna panga at the market grills', 'Boats came in heavy with tuna this week — the market grill stalls have panga (jaw) at local prices through the weekend. Lunch crowd clears it by 1pm.', 'food', 'Poblacion market', 'good', 'Local contributor', now() - interval '22 hours', now() + interval '60 hours'),
('Quiet right now: Alimanguan stretch', 'The northern beaches are near-empty on weekdays this month. If you want the sand to yourself, this is the window before the holiday season starts.', 'tip', 'Alimanguan', 'info', 'SANVIC conditions desk', now() - interval '30 hours', null),
('Pamuayan Falls flowing well', 'This week''s evening rain has the falls at their best flow of the month. Trail is a little slick in two spots — wear grippy footwear.', 'tip', 'Pamuayan', 'good', 'Local guides', now() - interval '40 hours', null),
('Heads up: barangay fiesta preparations', 'New Agutaya starts fiesta preparations next week — expect evening music near the barangay hall and busier eateries. Great time to try lechon if your trip overlaps.', 'event', 'New Agutaya', 'info', 'Barangay bulletin', now() - interval '50 hours', null);

-- barangays
insert into public.barangays (name, slug, description, latitude, longitude, label_visible, sort_order, is_active) values ('Poblacion', 'poblacion', 'Municipal center: market, transport terminals, airport, and Long Beach access.', 10.5318, 119.2822, true, 1, true);
insert into public.barangays (name, slug, description, latitude, longitude, label_visible, sort_order, is_active) values ('New Agutaya', 'new-agutaya', 'Heart of the Long Beach stretch — garden stays and beachfront grills.', 10.5122, 119.266, true, 2, true);
insert into public.barangays (name, slug, description, latitude, longitude, label_visible, sort_order, is_active) values ('San Isidro', 'san-isidro', 'Inland farms and hills northeast of the town center.', 10.567, 119.3187, true, 3, true);
insert into public.barangays (name, slug, description, latitude, longitude, label_visible, sort_order, is_active) values ('Alimanguan', 'alimanguan', 'Fishing village with the wild, empty northern beaches.', 10.59, 119.33, true, 4, true);
insert into public.barangays (name, slug, description, latitude, longitude, label_visible, sort_order, is_active) values ('Santo Niño', 'santo-nino', 'Quiet coastal barangay between Alimanguan and New Canipo.', 10.6506, 119.3348, true, 5, true);
insert into public.barangays (name, slug, description, latitude, longitude, label_visible, sort_order, is_active) values ('New Canipo', 'new-canipo', 'Northern coast and the jump-off toward Boayan Island.', 10.6969, 119.3078, true, 6, true);
insert into public.barangays (name, slug, description, latitude, longitude, label_visible, sort_order, is_active) values ('Binga', 'binga', 'San Vicente''s northernmost barangay.', 10.7612, 119.3144, true, 7, true);
insert into public.barangays (name, slug, description, latitude, longitude, label_visible, sort_order, is_active) values ('Kemdeng', 'kemdeng', 'Between Poblacion and Port Barton — waterfalls and inland trails.', 10.4797, 119.2545, true, 8, true);
insert into public.barangays (name, slug, description, latitude, longitude, label_visible, sort_order, is_active) values ('Port Barton', 'port-barton', 'The traveler village: island-hopping boats, bay beaches, café life.', 10.46, 119.195, true, 9, true);
insert into public.barangays (name, slug, description, latitude, longitude, label_visible, sort_order, is_active) values ('Caruray', 'caruray', 'Remote southwestern coast and islands, bordering Puerto Princesa.', 10.3701, 119.0155, true, 10, true);

-- Boundary polygons currently ship in the frontend
-- (src/data/barangayBoundaries.ts, PSA-derived). Import them into
-- barangay_boundaries when moving boundary editing server-side.
